apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-change
spec:
  selector:
    matchLabels:
      app: kube-image-pull-change
  replicas: 1
  template:
    metadata:
      labels:
        app: kube-image-pull-change
    spec:
      containers:
        - name: kube-image-pull-change
          image: "gocloudcoder/kube-image-pull:develop"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: kube-image-pull-change
spec:
  selector:
    app: kube-image-pull-change
  ports:
    - protocol: TCP
      port: 8888
      targetPort: http
  type: NodePort